# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-14 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='meta',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='shop',
            name='latlng',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='shop',
            name='meta',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
